name: fit_lit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.2
  dartz: ^0.10.1
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_remote_config: ^5.4.0
  firebase_storage: ^12.4.1
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1
  flutter_pdfview: ^1.4.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  get: ^4.6.6
  get_it: ^8.0.3
  http: ^1.3.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  toastification: ^2.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/fitlit-vr.png"

flutter_gen:
  output: lib/common/gen/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/json/
